site_name: MetaPrompt Documentation

# Site description (optional)
site_description: "MetaPrompt is a template engine for LLM prompts with support for writing prompts with prompts "

# Site URL (optional, useful for SEO and deployment)
site_url: "https://docs.metaprompt-lang.org"
edit_uri: blob/main/docs/
repo_url: https://github.com/promptware/metaprompt

# Theme
theme:
  name: readthedocs

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite

nav:
  - Home: index.md
  - Syntax: syntax.md
  # - Getting Started:
  #     - Introduction: getting_started/introduction.md
  #     - Installation: getting_started/installation.md
  # - Usage:
  #     - Basic Usage: usage/basic_usage.md
  #     - Advanced Features: usage/advanced_features.md
  # - API Reference:
  #     - API Overview: api/api_overview.md
  # - About:
  #     - License: about/license.md
  #     - Contributing: about/contributing.md

# Extra configuration for plugins (optional)
plugins:
  - search  # Default search plugin
  # Uncomment below for more plugins (you'll need to install them separately)
  # - mkdocs-mermaid2-plugin
  # - mkdocs-awesome-pages-plugin

# extra_javascript:
#   - javascripts/custom.js

# extra_css:
#   - stylesheets/custom.css

site_dir: site

docs_dir: docs
