//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\legov\OneDrive\Documents\GitHub\metaprompt\grammar\MetaPrompt.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MetaPromptParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface IMetaPromptListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaPromptParser.prompt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrompt([NotNull] MetaPromptParser.PromptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaPromptParser.prompt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrompt([NotNull] MetaPromptParser.PromptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaPromptParser.exprs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprs([NotNull] MetaPromptParser.ExprsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaPromptParser.exprs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprs([NotNull] MetaPromptParser.ExprsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaPromptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] MetaPromptParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaPromptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] MetaPromptParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaPromptParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr1([NotNull] MetaPromptParser.Expr1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaPromptParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr1([NotNull] MetaPromptParser.Expr1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaPromptParser.meta_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMeta_body([NotNull] MetaPromptParser.Meta_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaPromptParser.meta_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMeta_body([NotNull] MetaPromptParser.Meta_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaPromptParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterText([NotNull] MetaPromptParser.TextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaPromptParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitText([NotNull] MetaPromptParser.TextContext context);
}
