name: Python CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version, like '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements.txt  # If you have a requirements file
        pip install pytest

    - name: Run tests
      working-directory: python/
      env:
        PYTHONPATH: "${{ github.workspace }}/python/src"
      run: |
        pytest

    - name: Check build
      working-directory: python/
      env:
        PYTHONPATH: "${{ github.workspace }}/python/src"
      run: |
        pip install twine
        python setup.py sdist bdist_wheel
        twine check dist/*

    - name: Install and run
      working-directory: python/
      env:
        PYTHONPATH: "${{ github.workspace }}/python/src"
      run: |

        pip install -e .
        metaprompt
